# Generated by Django 4.1.1 on 2022-11-04 19:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habitacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(blank=True, max_length=45, verbose_name='Nombres')),
                ('apellidos', models.CharField(blank=True, max_length=45, verbose_name='Apellidos')),
                ('numeroDocumento', models.CharField(blank=True, max_length=45, verbose_name='Cédula de Ciudadanía')),
                ('telefono', models.CharField(blank=True, max_length=15, verbose_name='Teléfono')),
                ('correo', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('cantidadHabitaciones', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name=' Cantidad de Habitaciones')),
                ('numeroHuespedes', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name=' Número de Huespedes')),
                ('fechaIngreso', models.DateField(blank=True, help_text='MM/DA/AAAA', null=True, verbose_name='Check-In')),
                ('fechaSalida', models.DateField(blank=True, help_text='MM/DA/AAAA', null=True, verbose_name='Check-Out')),
                ('valorReserva', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Reserva')),
                ('metodoPago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia Bancaria', 'Transferencia Bancaria')], default='Efectivo', max_length=30, verbose_name='Método de Pago')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitacion.habitacion', verbose_name='Habitacion')),
                ('Reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.reserva', verbose_name='Reserva')),
            ],
        ),
    ]
