# Generated by Django 4.1.1 on 2022-11-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PQRS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(blank=True, max_length=45, verbose_name='Nombres')),
                ('apellidos', models.CharField(blank=True, max_length=50, verbose_name='Apellidos')),
                ('telefono', models.CharField(blank=True, max_length=15, verbose_name='Teléfono')),
                ('email', models.CharField(blank=True, max_length=50, verbose_name='Correo Electronico')),
                ('asunto', models.CharField(max_length=45, verbose_name='Asunto')),
                ('comentarioCliente', models.CharField(max_length=250, verbose_name='Comentario')),
                ('fechaCreacion', models.DateField(help_text='MM/DA/AAAA', verbose_name='Fecha')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
            ],
        ),
    ]
